# Generated by Django 4.2 on 2025-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamiento",
            name="motivo_reagendamiento",
            field=models.TextField(
                blank=True,
                help_text="El motivo por el cual el Jefetaller cambió la hora de la cita original.",
                null=True,
                verbose_name="Motivo de Reagendamiento",
            ),
        ),
    ]
