# Generated by Django 4.2 on 2025-11-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agendamiento_fecha_hora_programada'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.CharField(help_text='Código único o ID del llavero físico.', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Original', 'Original'), ('Duplicado', 'Duplicado'), ('Control', 'Control de Acceso'), ('Taller', 'Llave de Taller')], default='Original', max_length=50)),
                ('estado', models.CharField(choices=[('En Bodega', 'En Bodega'), ('Prestada', 'Prestada'), ('Perdida', 'Perdida'), ('Dada de Baja', 'Dada de Baja')], db_index=True, default='En Bodega', max_length=50)),
                ('poseedor_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_en_posesion', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llaves', to='accounts.vehiculo')),
            ],
            options={
                'verbose_name': 'Llave de Vehículo',
                'verbose_name_plural': 'Inventario de Llaves',
                'ordering': ['vehiculo__patente', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoLlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_hora_retiro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observaciones_retiro', models.TextField(blank=True, null=True)),
                ('observaciones_devolucion', models.TextField(blank=True, null=True)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='accounts.llavevehiculo')),
                ('usuario_retira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo de Llave',
                'verbose_name_plural': 'Historial de Préstamos',
                'ordering': ['-fecha_hora_retiro'],
            },
        ),
    ]
