# Generated by Django 4.2 on 2025-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_llavevehiculo_prestamollave'),
    ]

    operations = [
        migrations.AddField(
            model_name='llavevehiculo',
            name='motivo_reporte',
            field=models.TextField(blank=True, help_text='Razón por la cual la llave fue marcada como perdida o dañada.', null=True, verbose_name='Motivo del Reporte'),
        ),
        migrations.AlterField(
            model_name='llavevehiculo',
            name='estado',
            field=models.CharField(choices=[('En Bodega', 'En Bodega'), ('Prestada', 'Prestada'), ('Perdida', 'Perdida'), ('Dañada', 'Dañada'), ('Dada de Baja', 'Dada de Baja')], db_index=True, default='En Bodega', max_length=50),
        ),
    ]
