# Generated by Django 5.2.5 on 2025-09-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ordendocumento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='notificaciones/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='AgendamientoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Foto', 'Foto'), ('Informe', 'Informe'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='agendamientos_documentos/%Y/%m/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('agendamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='accounts.agendamiento')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
