# Generated by Django 4.2 on 2025-11-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_llavevehiculo_motivo_reporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='accounts.llavevehiculo')),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_llave_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Llave',
                'verbose_name_plural': 'Historiales de Estados de Llave',
                'ordering': ['-fecha'],
            },
        ),
    ]
