# Generated by Django 5.2.5 on 2025-10-03 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notificacion_archivo_agendamientodocumento'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamientodocumento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Documento de Agendamiento', 'verbose_name_plural': 'Documentos de Agendamiento'},
        ),
        migrations.AlterModelOptions(
            name='agendamientohistorial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Agendamiento', 'verbose_name_plural': 'Historiales de Agendamiento'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Orden de Servicio', 'verbose_name_plural': 'Órdenes de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='ordendocumento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Documento de Orden', 'verbose_name_plural': 'Documentos de Orden'},
        ),
        migrations.AlterModelOptions(
            name='ordenhistorialestado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Estado de Orden', 'verbose_name_plural': 'Historiales de Estado de Orden'},
        ),
        migrations.AlterModelOptions(
            name='ordenitem',
            options={'verbose_name': 'Ítem de Orden', 'verbose_name_plural': 'Ítems de Orden'},
        ),
        migrations.AlterModelOptions(
            name='ordenpausa',
            options={'ordering': ['-inicio'], 'verbose_name': 'Pausa de Orden', 'verbose_name_plural': 'Pausas de Orden'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='agendamiento',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenpausa',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordenpausa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], db_index=True, default='Programado', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('En Diagnostico', 'En Diagnóstico'), ('En Proceso', 'En Proceso'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], db_index=True, default='Ingresado', max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Mecanico', 'Supervisor'], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.', related_name='usuario_set', related_query_name='usuario', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuario_set', related_query_name='usuario', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chofer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Chofer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
