# Generated by Django 4.2 on 2025-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_llavehistorialestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendocumento',
            name='estado_en_carga',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Estado al Cargar'),
        ),
    ]
