# Generated by Django 5.2.5 on 2025-10-03 22:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_agendamientodocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='imagen_averia',
            field=models.ImageField(blank=True, null=True, upload_to='agendamientos_imagenes/%Y/%m/', verbose_name='Imagen de la avería'),
        ),
    ]
