# Generated by Django 5.2.5 on 2025-10-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_managers_agendamiento_imagen_averia'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='mecanico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Mecanico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Confirmado', 'Confirmado'), ('En Taller', 'En Taller'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], db_index=True, default='Programado', max_length=50),
        ),
    ]
