# Generated by Django 4.2 on 2025-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ordendocumento_estado_en_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendocumento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
