# Generated by Django 4.2 on 2025-11-10 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ordendocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='estado_repuesto',
            field=models.CharField(choices=[('N/A', 'No Aplica'), ('Pendiente', 'Pendiente de Aprobación'), ('Aprobado', 'Aprobado y Descontado'), ('Rechazado', 'Rechazado (Sin Stock)')], db_index=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='fecha_gestion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='gestionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='motivo_gestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
