# Generated by Django 5.2.5 on 2025-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_agendamiento_mecanico_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='solicita_grua',
            field=models.BooleanField(default=False, help_text='Marcar si el vehículo requiere ser movilizado por una grúa.'),
        ),
    ]
