# Generated by Django 4.2 on 2025-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ordenitem_estado_repuesto_ordenitem_fecha_gestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
