# Generated by Django 4.2 on 2025-11-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ordenitem_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del taller (Ej: Pepsico Maipú)', max_length=100, unique=True)),
                ('direccion', models.CharField(help_text='Dirección completa del taller', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='accounts.taller'),
        ),
    ]
