# Generated by Django 4.2 on 2025-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_taller_vehiculo_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='direccion_grua',
            field=models.CharField(blank=True, help_text='Dirección de retiro para la grúa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='grua_enviada',
            field=models.BooleanField(default=False, help_text='Marca si la grúa ya fue despachada'),
        ),
    ]
