# Generated by Django 4.2 on 2025-11-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_agendamiento_direccion_grua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='es_mantenimiento',
            field=models.BooleanField(default=False, help_text='Marcar si la solicitud es para un mantenimiento general predefinido.', verbose_name='Es Mantenimiento'),
        ),
    ]
