# Generated by Django 4.2 on 2025-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agendamiento_es_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='motivo_ingreso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
