# Generated by Django 4.2 on 2025-11-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_agendamiento_motivo_ingreso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamiento',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='agendamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['Finalizado', 'Cancelado']), _negated=True), fields=('vehiculo', 'fecha_hora_programada'), name='agendamiento_activo_unico_por_vehiculo_y_fecha'),
        ),
    ]
