# Generated by Django 4.2 on 2025-11-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_agendamiento_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamiento",
            name="imagen_averia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="agendamientos_imagenes/%Y/%m/",
                verbose_name="Adjuntar archivo (Foto, PDF, etc.)",
            ),
        ),
    ]
