# Generated by Django 4.2 on 2025-11-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_agendamiento_imagen_averia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre opcional para chats grupales.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "participantes",
                    models.ManyToManyField(
                        help_text="Usuarios que son parte de esta conversación.",
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participantes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala de Chat",
                "verbose_name_plural": "Salas de Chat",
                "ordering": ["-actualizado_en"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("contenido", models.TextField(verbose_name="Contenido del Mensaje")),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "leido_por",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mensajes_leidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leído por",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="accounts.chatroom",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["creado_en"],
            },
        ),
    ]
