# Generated by Django 4.2 on 2025-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_chatroom_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat_archivos/%Y/%m/",
                verbose_name="Archivo Adjunto",
            ),
        ),
    ]
