# Generated by Django 4.2 on 2025-11-18 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_chatmessage_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='oculto_para',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que han eliminado visualmente este chat.', related_name='chat_rooms_ocultos', to=settings.AUTH_USER_MODEL, verbose_name='Oculto Para'),
        ),
    ]
